<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBm7G650\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBm7G650/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBm7G650.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBm7G650\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBm7G650\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bm7G650',
    'container.build_id' => '82d57ce7',
    'container.build_time' => 1685896217,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBm7G650');
